export const Areas = [
    {
      text: 'צפון',
      value: '25',
      complex_id: { topArea: '25' },
      isGroupHeader: true,
    },
    {
      text: 'אזור חיפה והסביבה',
      value: '5',
      complex_id: { area: '5', topArea: '25' },
      groupID: '25',
    },
    {
      text: 'אזור הקריות',
      value: '6',
      complex_id: { area: '6', topArea: '25' },
      groupID: '25',
    },
    {
      text: 'אזור עכו נהריה והסביבה',
      value: '68',
      complex_id: { area: '68', topArea: '25' },
      groupID: '25',
    },
    {
      text: 'אזור הגליל העליון',
      value: '20',
      complex_id: { area: '20', topArea: '25' },
      groupID: '25',
    },
    {
      text: 'אזור הכנרת והסביבה',
      value: '14',
      complex_id: { area: '14', topArea: '25' },
      groupID: '25',
    },
    {
      text: 'אזור כרמיאל והסביבה',
      value: '53',
      complex_id: { area: '53', topArea: '25' },
      groupID: '25',
    },
    {
      text: 'אזור נצרת - שפרעם והסביבה',
      value: '91',
      complex_id: { area: '91', topArea: '25' },
      groupID: '25',
    },
    {
      text: 'אזור ראש פינה ועמק החולה',
      value: '96',
      complex_id: { area: '96', topArea: '25' },
      groupID: '25',
    },
    {
      text: 'אזור הגליל התחתון',
      value: '74',
      complex_id: { area: '74', topArea: '25' },
      groupID: '25',
    },
    {
      text: 'רמת הגולן',
      value: '83',
      complex_id: { area: '83', topArea: '25' },
      groupID: '25',
    },
    {
      text: 'חדרה, זכרון והעמקים',
      value: '101',
      complex_id: { topArea: '101' },
      isGroupHeader: true,
    },
    {
      text: 'אזור זכרון יעקב וחוף הכרמל',
      value: '67',
      complex_id: { area: '67', topArea: '101' },
      groupID: '101',
    },
    {
      text: 'אזור חדרה והסביבה',
      value: '15',
      complex_id: { area: '15', topArea: '101' },
      groupID: '101',
    },
    {
      text: 'אזור קיסריה והסביבה',
      value: '16',
      complex_id: { area: '16', topArea: '101' },
      groupID: '101',
    },
    {
      text: 'אזור יקנעם, טבעון והסביבה',
      value: '87',
      complex_id: { area: '87', topArea: '101' },
      groupID: '101',
    },
    {
      text: 'אזור עמק בית שאן',
      value: '93',
      complex_id: { area: '93', topArea: '101' },
      groupID: '101',
    },
    {
      text: 'אזור עפולה והעמקים',
      value: '13',
      complex_id: { area: '13', topArea: '101' },
      groupID: '101',
    },
    {
      text: 'אזור רמות מנשה',
      value: '97',
      complex_id: { area: '97', topArea: '101' },
      groupID: '101',
    },
    {
      text: 'שרון',
      value: '19',
      complex_id: { topArea: '19' },
      isGroupHeader: true,
    },
    {
      text: 'אזור נתניה והסביבה',
      value: '17',
      complex_id: { area: '17', topArea: '19' },
      groupID: '19',
    },
    {
      text: 'אזור רמת השרון והרצליה',
      value: '18',
      complex_id: { area: '18', topArea: '19' },
      groupID: '19',
    },
    {
      text: 'אזור רעננה וכפר סבא',
      value: '42',
      complex_id: { area: '42', topArea: '19' },
      groupID: '19',
    },
    {
      text: 'אזור הוד השרון והסביבה',
      value: '54',
      complex_id: { area: '54', topArea: '19' },
      groupID: '19',
    },
    {
      text: 'אזור דרום השרון',
      value: '81',
      complex_id: { area: '81', topArea: '19' },
      groupID: '19',
    },
    {
      text: 'אזור צפון השרון',
      value: '70',
      complex_id: { area: '70', topArea: '19' },
      groupID: '19',
    },
    {
      text: 'מרכז',
      value: '2',
      complex_id: { topArea: '2' },
      isGroupHeader: true,
    },
    {
      text: 'אזור תל אביב יפו',
      value: '1',
      complex_id: { area: '1', topArea: '2' },
      groupID: '2',
    },
    {
      text: 'אזור ראשון לציון והסביבה',
      value: '9',
      complex_id: { area: '9', topArea: '2' },
      groupID: '2',
    },
    {
      text: 'אזור חולון ובת ים',
      value: '11',
      complex_id: { area: '11', topArea: '2' },
      groupID: '2',
    },
    {
      text: 'אזור רמת גן וגבעתיים',
      value: '3',
      complex_id: { area: '3', topArea: '2' },
      groupID: '2',
    },
    {
      text: 'פתח תקווה והסביבה',
      value: '4',
      complex_id: { area: '4', topArea: '2' },
      groupID: '2',
    },
    {
      text: 'אזור ראש העין והסביבה',
      value: '71',
      complex_id: { area: '71', topArea: '2' },
      groupID: '2',
    },
    {
      text: 'בקעת אונו',
      value: '10',
      complex_id: { area: '10', topArea: '2' },
      groupID: '2',
    },
    {
      text: 'אזור רמלה - לוד',
      value: '51',
      complex_id: { area: '51', topArea: '2' },
      groupID: '2',
    },
    {
      text: 'אזור בני ברק וגבעת שמואל',
      value: '78',
      complex_id: { area: '78', topArea: '2' },
      groupID: '2',
    },
    {
      text: 'אזור עמק איילון',
      value: '92',
      complex_id: { area: '92', topArea: '2' },
      groupID: '2',
    },
    {
      text: 'אזור שוהם והסביבה',
      value: '98',
      complex_id: { area: '98', topArea: '2' },
      groupID: '2',
    },
    {
      text: 'אזור מודיעין והסביבה',
      value: '8',
      complex_id: { area: '8', topArea: '2' },
      groupID: '2',
    },
    {
      text: 'מחוז ירושלים',
      value: '100',
      complex_id: { topArea: '100' },
      isGroupHeader: true,
    },
    {
      text: 'אזור ירושלים',
      value: '7',
      complex_id: { area: '7', topArea: '100' },
      groupID: '100',
    },
    {
      text: 'אזור בית שמש והסביבה',
      value: '69',
      complex_id: { area: '69', topArea: '100' },
      groupID: '100',
    },
    {
      text: 'אזור הרי יהודה, מבשרת והסביבה',
      value: '86',
      complex_id: { area: '86', topArea: '100' },
      groupID: '100',
    },
    {
      text: 'אזור מעלה אדומים והסביבה',
      value: '90',
      complex_id: { area: '90', topArea: '100' },
      groupID: '100',
    },
    {
      text: 'שפלה ומישור החוף הדרומי',
      value: '41',
      complex_id: { topArea: '41' },
      isGroupHeader: true,
    },
    {
      text: 'אזור נס ציונה ורחובות',
      value: '12',
      complex_id: { area: '12', topArea: '41' },
      groupID: '41',
    },
    {
      text: 'אזור אשדוד, אשקלון והסביבה',
      value: '21',
      complex_id: { area: '21', topArea: '41' },
      groupID: '41',
    },
    {
      text: 'אזור גדרה - יבנה והסביבה',
      value: '52',
      complex_id: { area: '52', topArea: '41' },
      groupID: '41',
    },
    {
      text: 'אזור קרית גת והסביבה',
      value: '72',
      complex_id: { area: '72', topArea: '41' },
      groupID: '41',
    },
    {
      text: 'אזור השפלה',
      value: '99',
      complex_id: { area: '99', topArea: '41' },
      groupID: '41',
    },
    {
      text: 'יהודה ושומרון ובקעת הירדן',
      value: '75',
      complex_id: { topArea: '75' },
      isGroupHeader: true,
    },
    {
      text: 'אזור דרום הר חברון',
      value: '88',
      complex_id: { area: '88', topArea: '75' },
      groupID: '75',
    },
    {
      text: 'אזור ישובי השומרון',
      value: '45',
      complex_id: { area: '45', topArea: '75' },
      groupID: '75',
    },
    {
      text: 'אזור גוש עציון',
      value: '80',
      complex_id: { area: '80', topArea: '75' },
      groupID: '75',
    },
    {
      text: 'אזור בקעת הירדן וצפון ים המלח',
      value: '79',
      complex_id: { area: '79', topArea: '75' },
      groupID: '75',
    },
    {
      text: 'אזור אריאל וישובי יהודה',
      value: '77',
      complex_id: { area: '77', topArea: '75' },
      groupID: '75',
    },
    {
      text: 'דרום',
      value: '43',
      complex_id: { topArea: '43' },
      isGroupHeader: true,
    },
    {
      text: 'אזור באר שבע והסביבה',
      value: '22',
      complex_id: { area: '22', topArea: '43' },
      groupID: '43',
    },
    {
      text: 'אזור אילת והערבה',
      value: '24',
      complex_id: { area: '24', topArea: '43' },
      groupID: '43',
    },
    {
      text: 'אזור הר הנגב',
      value: '89',
      complex_id: { area: '89', topArea: '43' },
      groupID: '43',
    },
    {
      text: 'אזור הנגב המערבי',
      value: '85',
      complex_id: { area: '85', topArea: '43' },
      groupID: '43',
    },
    {
      text: 'אזור דרום ים המלח',
      value: '82',
      complex_id: { area: '82', topArea: '43' },
      groupID: '43',
    },
  ];