export const vehicleBrands = {
  Audi: { code: '1', label: 'אאודי' },
  Eberth: { code: '53', label: "אברת'" },
  Ottobianchi: { code: '96', label: 'אוטוביאנקי' },
  Oldsmobile: { code: '76', label: 'אולדסמוביל' },
  Austin: { code: '102', label: 'אוסטין' },
  Opal: { code: '2', label: 'אופל' },
  Eways: { code: '288', label: 'איווייס' },
  Ivoco: { code: '85', label: 'איווקו' },
  Infinity: { code: '3', label: 'אינפיניטי' },
  Isuzu: { code: '4', label: 'איסוזו' },
  LEVC: { code: '299', label: 'אל.אי.וי.סי / LEVC' },
  LTA: { code: '77', label: 'אל.טי.איי' },
  AlphaRomeo: { code: '5', label: 'אלפא רומיאו' },
  MG: { code: '6', label: "אם. ג'י. / MG" },
  AstonMartin: { code: '54', label: 'אסטון מרטין' },
  FEW: { code: '168', label: 'אף. אי. דאבל יו' },
  BMW: { code: '7', label: 'ב.מ.וו' },
  BYD: { code: '141', label: 'בי.ווי.די / BYD' },
  Buick: { code: '8', label: 'ביואיק' },
  Bentley: { code: '55', label: 'בנטלי' },
  JAC: { code: '200', label: "ג'י.איי.סי / JAC" },
  GAC: { code: '99', label: "ג'י.איי.סי/ GAC" },
  GMC: { code: '9', label: "ג'י.אם.סי / GMC" },
  Geo: { code: '94', label: "ג'יאו / Geo" },
  Geely: { code: '177', label: "ג'ילי - Geely" },
  Jeep: { code: '10', label: "ג'יפ / Jeep" },
  JeepTaar: { code: '59', label: "ג'יפ תע''ר" },
  Genesis: { code: '93', label: "ג'נסיס" },
  GreatWall: { code: '11', label: 'גרייט וול' },
  Dacia: { code: '12', label: "דאצ'יה" },
  dodge: { code: '13', label: "דודג'" },
  Dongfeng: { code: '88', label: 'דונגפנג' },
  DS: { code: '14', label: 'די.אס / DS' },
  Daewoo: { code: '60', label: 'דייהו' },
  Daihatsu: { code: '15', label: 'דייהטסו' },
  Hammer: { code: '16', label: 'האמר' },
  HONGQI: { code: '301', label: "הונגצ'י / HONGQI" },
  Honda: { code: '17', label: 'הונדה' },
  HINO: { code: '95', label: 'הינו  HINO' },
  Volvo: { code: '18', label: 'וולוו' },
  Tata: { code: '87', label: 'טאטא' },
  Toyota: { code: '19', label: 'טויוטה' },
  Tesla: { code: '62', label: 'טסלה' },
  Jaguar: { code: '20', label: 'יגואר' },
  Hyundai: { code: '21', label: 'יונדאי' },
  Lada: { code: '80', label: 'לאדה' },
  Lincoln: { code: '23', label: 'לינקולן' },
  Lychee: { code: '98', label: "ליצ'י" },
  Lamborghini: { code: '63', label: 'למבורגיני' },
  LandRover: { code: '24', label: 'לנד רובר' },
  Lancia: { code: '25', label: "לנצ'יה" },
  Lexus: { code: '26', label: 'לקסוס' },
  Mazda: { code: '27', label: 'מאזדה' },
  Man: { code: '86', label: 'מאן' },
  Maserati: { code: '28', label: 'מזראטי' },
  sexual: { code: '29', label: 'מיני' },
  Mitsubishi: { code: '30', label: 'מיצובישי' },
  Maxus: { code: '89', label: 'מקסוס' },
  Mercedes: { code: '31', label: 'מרצדס' },
  Nissan: { code: '32', label: 'ניסאן' },
  Nanjing: { code: '78', label: "ננג'ינג" },
  Saab: { code: '33', label: 'סאאב' },
  SunLiving: { code: '302', label: 'סאן ליוינג / Sun Living' },
  Ssangyong: { code: '34', label: 'סאנגיונג' },
  Sunshine: { code: '56', label: 'סאנשיין' },
  Subaru: { code: '35', label: 'סובארו' },
  Suzuki: { code: '36', label: 'סוזוקי' },
  Seat: { code: '37', label: 'סיאט' },
  Citroen: { code: '38', label: 'סיטרואן' },
  Smart: { code: '39', label: 'סמארט' },
  Sentro: { code: '97', label: 'סנטרו' },
  Skoda: { code: '40', label: 'סקודה' },
  Skywell: { code: '300', label: 'סקייוול' },
  Seres: { code: '287', label: 'סרס / SERES' },
  Volkswagen: { code: '41', label: 'פולקסווגן' },
  Pontiac: { code: '42', label: 'פונטיאק' },
  Ford: { code: '43', label: 'פורד' },
  porsche: { code: '44', label: 'פורשה' },
  Piaggio: { code: '90', label: "פיאג'ו" },
  Fiat: { code: '45', label: 'פיאט' },
  Peugeot: { code: '46', label: "פיג'ו" },
  Ferrari: { code: '57', label: 'פרארי' },
  Cadillac: { code: '47', label: 'קאדילק' },
  copra: { code: '92', label: 'קופרה' },
  Kia: { code: '48', label: 'קיה' },
  Chrysler: { code: '49', label: 'קרייזלר' },
  Rover: { code: '50', label: 'רובר' },
  Renault: { code: '51', label: 'רנו' },
  Chevrolet: { code: '52', label: 'שברולט' },
} as const;
